Add windows arm build (#663)
* Adding windows arm build

- Updatig to pybind11 3.0.1
  - 3.0.0 lead to a visibility compiler error on windows arm
  - 3.0.1 includes a fix for this

* addressing flang errors

- attempting to set hdf and netcdf directories

nullifying radiator
- select type seems to lose the pointer attribute on fortran derived
  types
- this lead to an error similar to the one below
- moving the deallocate to after the select type made flang happy

musica/src/tuvx/interface_radiator_map.F90:200:18: error: Name in DEALLOCATE statement must have the ALLOCATABLE or POINTER attribute
        deallocate(f_radiator)

                   ^^^^^^^^^^

* Disable carma tests on arm windows

- only installing ussa1976 on non widows non arm systems
- disabling carma on windows arm, some sort of internal error and
  I don't know how to debug it since I don't have a windows arm machine
- arm wheel build

* skipping wheels on windows for python <3.11

- removing intel dockerfile

* adding setup windows arm to wheels

* testing python files with cibuildwheel

- moving tuvx data into configs
- removing redundant full_config files
- updating C++/Fortran/C tests to use new tuvx data location

* ignoring ussa1976 on i686

* removing verbose output from tests

* testing a shorter build

* removing cli test to see if that's causing the hangup

* Using copy of tuvx data

- windows fortran was timing out on mkdir -p
- I don't know why, but disabling diagnostics for tests should fix this
- this commit copies files from tuvx to allow us to do that
- something in this pr probably affected this, but I don't know why
  since all I did was change a path...

* adding other python versions

* disabling tuvx for all

* skipping tests on i686

* renabling tuvx, dropping python versions

* fixing tuvx configs

* excluding tuvx tests on windows

* ignoring a different way

* quotes